language: python
python:
  - 3.6

install: pip install -r requirements.txt
before_script: export PYTHONPATH=$PYTHONPATH:$(pwd)/src
script: python -m unittest discover tests
docker-compose build redis

