language: python
python:
  - 3.6

install: pip install -r requirements.txt
before_script: export PYTHONPATH=$PYTHONPATH:$(pwd)/src

jobs:
  include:
    script:
      - python -m unittest discover tests
      - docker-compose build redis
      - docker-compose build mysql
      - docker-compose build flask
      - docker-compose build nginx
#script: python -m unittest discover tests
#docker-compose build redis

