language: python
python:
  - 3.6

install: pip install -r requirements.txt
before_script: export PYTHONPATH=$PYTHONPATH:$(pwd)/src

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.23.2
    - secure: "Q9b6/Z0DMpOMqXBrP4S93S/6AQekmsO/sGvJ7FzaBRc+i4sZ06Ik0BmkChvDuvRRR6wku4pmARbD76+RiAcZfBxzdt7gJKLnlYh6R3vcntbKPuL9a9QNXlj6szBY10sbBho3mZsH1DuUZ/HS6oc1pLCYd5loy2J5eQd8OaHcUU50hpuTXixdqOcdQ+UO+fbz1D28HPLa4jBApAmq8WjBwyRJb047PJAr2pJ5YoYIYmm8tMyO8QryGlhlitFNpTvG6LOEET6AVQdCXLIozsLxtc9iZRCizirkPpTk7AE1wz9C2q/rIxQjRm1Yp/+Plw04N/swQZZkc7zLSwTT/ZEs4vKoE5qG9iwIf8o2SMbD1stlEhLYdEeKrUoG23pZt5Sjpj2gMofqv1BwAUKxejEK+8GE8Ua5gB+pjkoGfs5x6HQ90Ta3HnFPduCxxqK4eAdVRfbN3ZCH2Zqh5Mxh87QzrzLBocZVxuiUnweDwzmO1/OFVaD4Fouff3CnUht08VbeHPSZqRC6JPCy94WVQSwZhGib+HmVnx5OdYYlzU+ytl9nDmTuoio0ElFbYyNYjyVzRw4cL/CDBITvBmeXwz3R/GfBJkveQeiSCkKJSprChquSYoQAKBP4usKW/dtXGAfjuQPjk5M9ngUnKidvXMIdiHpJzJczls6bsCKslhw1uqg="
    - secure: "ZBeD1zV2WozvuMngCfXjzYpiPXivDde6yDMQ6nsXz9QkFpBBUq9ayn7mG0ZesnOqKjnC6SpfM9PM6TKHTCpNIwCLKXx6i0Q914gbMmOqG7buZ1yMZYSRNNL2AB/ES7FHi97CqKaf86XX3MqoLs70O7FJt+A8bA/oSg5MiNL5eOqXs2NLtl6t6bRxa28aZii165EiXlhAza6ZXEJuT+qTqkW/9TpV4izgIWCtqRlUtBq6Td4SWBiqCG9dJjha02q2GM/2Tf8FBUIfWdrBpyx7WCXDcEwVAkk4C2gTlJlMgFTivsw7hljUwiZIFkrrzsrrkAnGRSVO7fzTURBeMTm9vUCuCmVCOjMu0eXUjcxPXV4gpDyTkVmyIHZBN9D4cF+6wZ/iUUcKFc4u7yZ2DmQZAgLrQw7svhELcG+Uvypf72LV+hP7JcTdPu9YBsfgCavtJKuwD+1VOeu3VC0z6n9HAuCtMoVJNEpCrWldM4desmCkX3ERp3Uq5glu4ys2kJiDitI7k/KdEeEbtdsCViyOdv9Ta8LDy04/U1/DiN7ezJXRemT7s6lulNEpLtP2+275kopn5xh0LAxEcyvMOmh4bGamJ54LaSpS8z3RUWsQBvYqshK+L+Hu1o8HoZHNowBhbvYGZnDMewpFiHn+hODeaiUcuXvIa+y81WBb98A3v6I="

jobs:
  include:
    script:
      - python -m unittest discover tests
      - docker-compose build redis
      - docker-compose build mysql
      - docker-compose build flask
      - docker-compose build nginx
#script: python -m unittest discover tests
#docker-compose build redis

