version: '3'

services:

  mysql:
    container_name: 'dev-reward-mysql'
    image: "mysql:5.7"
    ports:
      - "3306:3306"

  redis:
    container_name: 'dev-reward-redis'
    image: 'redis:5.0.3'
    ports:
      - '6379:6379'
